site_name: iDEC 2024 | SynthImmunol_NMU

theme:
  name: material
  logo: img/idec-wiki-logo-white-bg.png
  favicon: img/idec-wiki-logo.png

  palette:
    primary: light blue
    accent: blue

  features:
    - navigation.sections

markdown_extensions:
  - footnotes

  # For MathJax
  - pymdownx.arithmatex:
      generic: true

  # For buttons and image control
  - attr_list

extra_javascript:
  # For MathJax: https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  # For sortable data tables: https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

edit_uri: blob/main/docs/

repo_url: https://github.com/idec-teams/2024_SynthImmunol_NMU

copyright: Copyright &copy; 2024 iDEC. CC-BY-4.0 | The International Directed Evolution Competition (iDEC) is a Scottish Charitable Incorporate Organisation (SCIO), registered in Scotland, with charity number：SC050826

nav:
  - Home: index.md
  - Team: team.md
  - Project:
      - Background: project/background.md
      - Results: project/results.md
  - Documentation:
      - Protocols: documentation/protocols.md
      - Lab notebook: documentation/notebook.md
  - Some useful features: useful_features.md